package io.github.first_uninteresting_username.projects_list

object Routes {
    const val PROTOTYPE = "prototype"
    const val HOME = "home"
    const val SETTINGS = "settings"
    const val ABOUT = "about"
    const val LICENSES = "licenses"
    const val NEW_PROJECT = "new_project"
    const val PROJECT = "project"
    const val PROJECT_ID_ARG = "projectId"
    const val PROJECT_ROUTE = "$PROJECT/{$PROJECT_ID_ARG}"
    const val EDIT_PROJECT = "edit_project"
    const val EDIT_PROJECT_ROUTE = "$EDIT_PROJECT/{$PROJECT_ID_ARG}"
    const val NEW_TASK = "new_task"
    const val NEW_TASK_ROUTE = "$NEW_TASK/{$PROJECT_ID_ARG}"
    const val TASK = "task"
    const val TASK_ID_ARG = "taskId"
    const val TASK_ROUTE = "$TASK/{$PROJECT_ID_ARG}/{$TASK_ID_ARG}"
    const val EDIT_TASK = "edit_task"
    const val EDIT_TASK_ROUTE = "$EDIT_TASK/{$PROJECT_ID_ARG}/{$TASK_ID_ARG}"
    const val SEARCH = "search"
    const val FILTER = "filter"
    const val SORT = "sort"
    const val TASK_SEARCH = "task_search"
    const val TASK_SEARCH_ROUTE = "$TASK_SEARCH/{$PROJECT_ID_ARG}"
    const val TASK_FILTER = "task_filter"
    const val TASK_SORT = "task_sort"

    fun projectRoute(projectId: String) = "$PROJECT/$projectId"
    fun editProjectRoute(projectId: String) = "$EDIT_PROJECT/$projectId"
    fun newTaskRoute(projectId: String) = "$NEW_TASK/$projectId"
    fun taskRoute(projectId: String, taskId: String) = "$TASK/$projectId/$taskId"
    fun editTaskRoute(projectId: String, taskId: String) = "$EDIT_TASK/$projectId/$taskId"
    fun taskSearchRoute(projectId: String) = "$TASK_SEARCH/$projectId"
}
